# Generated by Django 5.0.6 on 2024-06-12 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_expense', models.DateTimeField()),
                ('purpose', models.CharField(max_length=300)),
                ('nature', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('other', 'other')], max_length=300)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_income', models.DateField()),
                ('source', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('nature', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly'), ('other', 'other')], max_length=100)),
                ('referal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('responsible', models.CharField(max_length=300)),
                ('amount', models.PositiveIntegerField()),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=200)),
                ('date_created', models.DateField()),
                ('status', models.CharField(choices=[('advanced', 'advanced'), ('received', 'received')], max_length=200)),
                ('payment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.PositiveIntegerField()),
                ('payment_date', models.DateField()),
                ('loan_status', models.CharField(choices=[('unpaid', 'unpaid'), ('partly_paid', 'partly_paid'), ('fully_paid', 'fully_paid')], max_length=200)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmgt_app.loan')),
            ],
        ),
    ]
