# Generated by Django 5.0.6 on 2024-06-12 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmgt_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date_of_expense',
            field=models.DateField(),
        ),
    ]
