# Generated by Django 5.0.6 on 2024-06-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmgt_app', '0004_alter_loan_date_created_alter_loan_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_acquisition', models.DateField()),
                ('asset_name', models.CharField(max_length=300)),
                ('asset_cost', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('refere1', models.CharField(max_length=100)),
                ('refere1_phone', models.PositiveIntegerField()),
                ('refere2', models.CharField(max_length=100)),
                ('refere2_phone', models.PositiveIntegerField()),
            ],
        ),
    ]
